namespace: plopoyop
name: warpgate
version: 1.0.0
readme: README.md
authors:
  - Clément Hubert

description: Ansible collection to install and configure Warpgate

license:
  - MPL-2.0

tags:
  - infrastructure
  - linux
  - warpgate
  - bastion
  - ssh
  - proxy
  - http
  - mysql
  - postgresql

dependencies: {}

repository: 'https://github.com/plopoyop/ansible-collection-warpgate'
homepage: 'https://github.com/plopoyop/ansible-collection-warpgate'
issues: 'https://github.com/plopoyop/ansible-collection-warpgate/issues'

build_ignore:
  - tests
  - collections
  - .devbox
  - .pytest_cache
  - .ruff_cache
  - __pycache__
  - .github
  - .ansible-lint
  - .yamllint
  - .pre-commit-config.yaml
  - .gitignore
  - .ansible
  - .task
  - Taskfile.yml
  - devbox.json
  - devbox.lock
  - ruff.toml
  - pytest.ini
  - renovate.json
  - CHANGELOG.md
