---
galaxy_info:
  author: "Clément Hubert"
  role_name: "install"
  description: "Install warpgate"

  license: "MPL2"

  min_ansible_version: "2.1"

  galaxy_tags:
    - "warpgate"
    - "ssh"
    - "bastion"
    - "proxy"
    - "http"
    - "mysql"
    - "postgresql"

  platforms:
    - name: "Debian"
      versions:
        - "trixie"
        - "bookworm"
    - name: "EL"
      versions:
        - "9"
        - "10"

dependencies: []
